from fpdf import FPDF

class PDFReport(FPDF):
    def header(self) -> None:
        self.set_font("Arial", "B", 16)
        self.cell(0, 10, "MediAssist - Clinical SOAP Note", 0, 1, "C")
        self.ln(5)
        self.set_font("Arial", "B", 50)
        self.set_text_color(220, 220, 220)
        try:
            with self.rotation(45, 100, 150):
                self.text(30, 190, "CONFIDENTIAL")
        except AttributeError:
            self.text(60, 150, "CONFIDENTIAL")
        self.set_text_color(0, 0, 0)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()} - Generated by MediAssist AI Scribe", 0, 0, "C")

    def chapter_title(self, label: str) -> None:
        self.set_font("Arial", "B", 12)
        self.set_fill_color(200, 220, 255)
        self.cell(0, 10, f"{label}", 0, 1, "L", 1)
        self.ln(2)

    def chapter_body(self, text: str) -> None:
        self.set_font("Arial", "", 11)
        self.multi_cell(0, 7, text)
        self.ln(5)
